version: 2
updates:
- package-ecosystem: cargo
  directory: "/robohash"
  schedule:
    interval: daily
    time: "08:00"
  open-pull-requests-limit: 10
- package-ecosystem: cargo
  directory: "/robonames"
  schedule:
    interval: daily
    time: "08:00"
  open-pull-requests-limit: 10
- package-ecosystem: cargo
  directory: "/wasm"
  schedule:
    interval: daily
    time: "08:00"
  open-pull-requests-limit: 10
